
export default ({ ui, api, name }) => {

  const build = api ? 'dist' : 'lib'

  const scripts = {
    'build': `rm -rf ${build}; mkdir ${build}; babel src --out-dir ${build} --copy-files`,
    'build:dev': 'npm run build -- --watch',
    'test': 'mocha --options .mocha.opts',
    'test:dev': 'npx watch \'npm run test\' src',
    'lint': 'eslint src --fix'
  }

  if (!api) {
    scripts['prepublishOnly'] = 'npm run link && npm run test && npm run build'
    scripts['release:patch'] = 'npm version patch && npm publish'
    scripts['release:minor'] = 'npm version minor && npm publish'
    scripts['release:major'] = 'npm version major && npm publish'
  } else {
    scripts['start'] = 'npm run link && npm run test && npm run build && npm run serve'
    scripts['serve'] = 'node ./scripts/serve.js'
  }

  if (ui) {
    scripts['webpack'] = 'NODE_ENV=production webpack'
    scripts['webpack:dev'] = 'NODE_ENV=development webpack-dev-server'
  }

  const pkg = {
    name,
    version: '0.0.1',
    main: build,
    scripts,
    keywords: [],
    author: 'BenZed',
    license: 'ISC',
    description: 'generated by BenZed\'s create-project dev tool'
  }

  return pkg
}

export const devDependencies = () => [
  '@benzed/dev'
]

export const dependencies = ({ ui }) => [
  ui && '@benzed/react'
]
